version = 0.1
[default.deploy.parameters]
stack_name = "rfp-classification"
resolve_s3 = true
s3_prefix = "rfp-classification"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []
disable_rollback = true
SourceBucketName = "rfpsamples1"
DestinationBucketName = "rfpsamples-doc"
parameter_overrides = "SourceBucketName=\"rfpsamples1\" DestinationBucketName=\"rfpsamplesdoc\""
