AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
  RFQ classification pipeline

  SAM Template for RFQ Document Classification

Globals:
  Function:
    Runtime: python3.11
    Handler: main.lambda_handler
    Architectures:
      - x86_64
    Timeout: 200
    Tracing: Active
    Layers:
      - !Sub arn:aws:lambda:${AWS::Region}:017000801446:layer:AWSLambdaPowertoolsPythonV2-Arm64:51

Parameters:
  SourceBucketName:
    Type: String
  DestinationBucketName:
    Type: String

Resources:
  ## S3 bucket
  SourceBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref SourceBucketName    
  DestinationBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref DestinationBucketName  
  UploadTriggerFunction:
      Type: AWS::Serverless::Function
      Properties:
        CodeUri: src/upload_trigger/
        Policies:
          - AmazonS3FullAccess
          - AWSLambda_FullAccess
          - AWSStepFunctionsFullAccess
          - CloudWatchLogsFullAccess
        Events:
          FileUpload:
            Type: S3
            Properties:
              Bucket: !Ref SourceBucket
              Events: s3:ObjectCreated:*
              Filter: 
                S3Key:
                  Rules:
                    - Name: suffix
                      Value: '.zip' 
